### ISSUE TITLE
Event Priority: Part 2

### ISSUE THREAD

**Issue by LostLogia4** [dragonjet/KC3Kai#461] opened 2015-08-02 23:52 UTC
One of the milestones for the summer 2015 event.
If left unpatched, we might have the "battle avoided" bug like in air and night battle nodes before this.

...Having said that though, i didn't record the API call back then... too bad...

----

edited by @dragonjet onwards

:white_check_mark:  #533 New plane system
:white_check_mark:  #578 Combined fleet prediction indexing

**Comment by ethrundr** [comment] 2015-08-03 01:39
Since we're now talking about the battle mode during event, might also better to revamp the layout to accommodate 12 ships in combined fleet, as well as detecting enemy formation from the API calls.

My suggestion is to make a temporary layout which will only be there during event, than replaced to the original (current) layout once event ends. The layout will be by default created to store details of 12 ships.

Second option is to make two permanent layout that can switch according to the map system we're facing: current layout on single-fleet maps and new 12-ships layout on combined-fleet maps.

**Comment by dragonjet** [comment] 2015-08-03 01:40
right now only there two are the combined-related APIs supported:

`api_req_hensei/combined` - on fleet management, button to combine or not, which will set our internal flags `true` or `false` to be used later on

`api_req_combined_battle/battle_water` - a combined fleet node

I think there will be more combined nodes later on and we could probably just publish on webstore ever 2 or 3 days after event.

**Comment by dragonjet** [comment] 2015-08-03 01:44
ah @ethrundr you can see on vertical layout there's a "combined" button there which will show you the 12 ships at once.

been designing this for the horizontal as well

![natsuiro theme2](https://cloud.githubusercontent.com/assets/557312/9029313/31aaaa80-39c4-11e5-8420-6f7229195203.png)

**Comment by ethrundr** [comment] 2015-08-03 01:47
ah, I rarely used the vertical one xD
always used the horizontal version in a detached window for quite some time now, since I can move it to my other monitor, so I can put two browser windows on my main monitor: KC and the wikia :smile:

**Comment by dragonjet** [comment] 2015-08-04 02:44
ah @LostLogia4 is it alright to change the title to "Support Event-specific API calls"?

**Comment by LostLogia4** [comment] 2015-08-04 06:41
Green light flashed :+1:

**Comment by LostLogia4** [comment] 2015-08-04 06:45
@dragonjet Not sure if there are other event-exclusive API calls apart from combined fleet, but sure.

**Comment by c933103** [comment] 2015-08-04 09:20
Is the original post for the issue more about what to display if there are any new unknown node appear..?

**Comment by ethrundr** [comment] 2015-08-04 10:44
@c933103 the original post is about the API and nodes specific to the event map: combined fleet maps and nodes, as well as other maps and nodes, since they all have possibilities using different API call than the normal map nodes.

**Comment by dragonjet** [comment] 2015-08-04 11:15
hm it's all the same thing XD kind of like, making sure everything should work as expected even after the introduction of event maps

**Comment by LostLogia4** [comment] 2015-08-05 06:29
@c933103 Original post is about Combined Fleet API call, dj requested to broaden this for any possible event-exclusive APIs.

That, too, we have Map 5 if we need to test support expeditions as well.

**Comment by c933103** [comment] 2015-08-06 18:30
Fleet command facility and difficulty selection are also event specific, but is there anything left out? Probably should make a check list on what are event-only

**Comment by dragonjet** [comment] 2015-08-07 04:39
ah FCF is not yet supported yes. They will look like still in taiha on the panel even if retreated.

So currently:
* Detect event difficulty selection
* FCF

**Comment by Crazyteitoku** [comment] 2015-08-07 05:17
Fleet locking, but the issue is really minuscule honestly. It comes into play when the user either plays using easy mode and/or alternates between easy and other difficulty modes. You could probably just send out a little reminder (a-la morale/resupply red box) to tell them that certain ships cannot be used. Again, trivial.

**Comment by ReiFan49** [comment] 2015-08-10 12:12
`api_stamp` on ships
and i don't really remember api variable on mapinfo,

however either both of them match or either of them is zero, is acceptable.

battle prediction only affects fleet of 6,
for quests tracking fleet of 12, need to shift index of 7 to 13, and so on. (iirc, need to reconfirm later on)

**Comment by dragonjet** [comment] 2015-08-10 22:08
hmm you're right about the combined fleet indexing

has anyone tried out having to use FCF?

**Comment by bamboo3250** [comment] 2015-08-11 02:25
Combined Fleet battle API (Surface Task Force)

`/kcsapi/api_req_combined_battle/battle_water`
```
{
  "api_result": 1,
  "api_result_msg": "成功",
  "api_data": {
    "api_deck_id": "1",
    "api_ship_ke": [
      -1,
      527,
      527,
      622,
      622,
      575,
      575
    ],
    "api_ship_lv": [
      -1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "api_nowhps": [
      -1,
      53,
      57,
      48,
      56,
      92,
      92,
      76,
      76,
      43,
      43,
      35,
      35
    ],
    "api_maxhps": [
      -1,
      53,
      57,
      48,
      56,
      92,
      92,
      76,
      76,
      43,
      43,
      35,
      35
    ],
    "api_nowhps_combined": [
      -1,
      24,
      32,
      32,
      32,
      32,
      38
    ],
    "api_maxhps_combined": [
      -1,
      32,
      32,
      32,
      32,
      32,
      45
    ],
    "api_midnight_flag": 0,
    "api_eSlot": [
      [
        505,
        506,
        515,
        525,
        -1
      ],
      [
        505,
        506,
        515,
        525,
        -1
      ],
      [
        502,
        502,
        559,
        -1,
        -1
      ],
      [
        502,
        502,
        559,
        -1,
        -1
      ],
      [
        502,
        545,
        542,
        -1,
        -1
      ],
      [
        502,
        545,
        542,
        -1,
        -1
      ]
    ],
    "api_eKyouka": [
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ]
    ],
    "api_fParam": [
      [
        78,
        74,
        42,
        73
      ],
      [
        84,
        84,
        37,
        77
      ],
      [
        25,
        0,
        63,
        52
      ],
      [
        82,
        84,
        53,
        79
      ],
      [
        105,
        0,
        94,
        90
      ],
      [
        102,
        0,
        90,
        92
      ]
    ],
    "api_eParam": [
      [
        68,
        48,
        40,
        70
      ],
      [
        68,
        48,
        40,
        70
      ],
      [
        58,
        88,
        44,
        36
      ],
      [
        58,
        88,
        44,
        36
      ],
      [
        38,
        60,
        30,
        22
      ],
      [
        38,
        60,
        30,
        22
      ]
    ],
    "api_fParam_combined": [
      [
        48,
        79,
        34,
        49
      ],
      [
        48,
        79,
        27,
        49
      ],
      [
        35,
        79,
        36,
        49
      ],
      [
        50,
        80,
        27,
        49
      ],
      [
        50,
        80,
        24,
        49
      ],
      [
        66,
        79,
        36,
        69
      ]
    ],
    "api_search": [
      1,
      1
    ],
    "api_formation": [
      "12",
      2,
      1
    ],
    "api_stage_flag": [
      1,
      1,
      1
    ],
    "api_kouku": {
      "api_plane_from": [
        [
          3
        ],
        [
          -1
        ]
      ],
      "api_stage1": {
        "api_f_count": 51,
        "api_f_lostcount": 0,
        "api_e_count": 0,
        "api_e_lostcount": 0,
        "api_disp_seiku": 1,
        "api_touch_plane": [
          -1,
          -1
        ]
      },
      "api_stage2": {
        "api_f_count": 9,
        "api_f_lostcount": 3,
        "api_e_count": 0,
        "api_e_lostcount": 0
      },
      "api_stage3": {
        "api_frai_flag": [
          -1,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "api_erai_flag": [
          -1,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "api_fbak_flag": [
          -1,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "api_ebak_flag": [
          -1,
          0,
          0,
          1,
          0,
          0,
          1
        ],
        "api_fcl_flag": [
          -1,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "api_ecl_flag": [
          -1,
          0,
          0,
          0,
          0,
          0,
          1
        ],
        "api_fdam": [
          -1,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "api_edam": [
          -1,
          0,
          0,
          0,
          0,
          0,
          45
        ]
      },
      "api_stage3_combined": {
        "api_frai_flag": [
          -1,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "api_fbak_flag": [
          -1,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "api_fcl_flag": [
          -1,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "api_fdam": [
          -1,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      }
    },
    "api_support_flag": 0,
    "api_support_info": null,
    "api_opening_flag": 0,
    "api_opening_atack": null,
    "api_hourai_flag": [
      1,
      1,
      1,
      1
    ],
    "api_hougeki1": {
      "api_at_list": [
        -1,
        5,
        8,
        6,
        4,
        10,
        2,
        9,
        1,
        11,
        3
      ],
      "api_at_type": [
        -1,
        2,
        0,
        2,
        2,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_df_list": [
        -1,
        [
          9,
          9
        ],
        [
          2
        ],
        [
          7,
          7
        ],
        [
          11,
          11
        ],
        [
          5
        ],
        [
          8
        ],
        [
          2
        ],
        [
          8
        ],
        [
          6
        ],
        [
          10
        ]
      ],
      "api_si_list": [
        -1,
        [
          137,
          137
        ],
        [
          505
        ],
        [
          137,
          133
        ],
        [
          90,
          90
        ],
        [
          502
        ],
        [
          90
        ],
        [
          502
        ],
        [
          50
        ],
        [
          502
        ],
        [
          -1
        ]
      ],
      "api_cl_list": [
        -1,
        [
          1,
          1
        ],
        [
          1
        ],
        [
          2,
          1
        ],
        [
          1,
          1
        ],
        [
          1
        ],
        [
          0
        ],
        [
          2
        ],
        [
          1
        ],
        [
          0
        ],
        [
          0
        ]
      ],
      "api_damage": [
        -1,
        [
          3,
          5
        ],
        [
          5
        ],
        [
          241,
          0
        ],
        [
          3,
          4
        ],
        [
          11.1
        ],
        [
          0
        ],
        [
          5
        ],
        [
          36
        ],
        [
          0
        ],
        [
          0
        ]
      ]
    },
    "api_hougeki2": {
      "api_at_list": [
        -1,
        1,
        8,
        2,
        9,
        3,
        10,
        4,
        5,
        6
      ],
      "api_at_type": [
        -1,
        0,
        0,
        2,
        0,
        0,
        0,
        0,
        2,
        0
      ],
      "api_df_list": [
        -1,
        [
          8
        ],
        [
          4
        ],
        [
          11,
          11
        ],
        [
          3
        ],
        [
          8
        ],
        [
          5
        ],
        [
          8
        ],
        [
          8,
          8
        ],
        [
          9
        ]
      ],
      "api_si_list": [
        -1,
        [
          50
        ],
        [
          505
        ],
        [
          90,
          90
        ],
        [
          502
        ],
        [
          -1
        ],
        [
          502
        ],
        [
          90
        ],
        [
          137,
          137
        ],
        [
          137
        ]
      ],
      "api_cl_list": [
        -1,
        [
          0
        ],
        [
          0
        ],
        [
          1,
          1
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          1,
          2
        ],
        [
          0
        ]
      ],
      "api_damage": [
        -1,
        [
          0
        ],
        [
          0
        ],
        [
          122,
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          144,
          222
        ],
        [
          0
        ]
      ]
    },
    "api_hougeki3": {
      "api_at_list": [
        -1,
        6,
        10,
        1,
        9,
        2,
        5,
        3,
        4
      ],
      "api_at_type": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_df_list": [
        -1,
        [
          9
        ],
        [
          5
        ],
        [
          10
        ],
        [
          1
        ],
        [
          9
        ],
        [
          9
        ],
        [
          10
        ],
        [
          9
        ]
      ],
      "api_si_list": [
        -1,
        [
          6
        ],
        [
          502
        ],
        [
          63
        ],
        [
          502
        ],
        [
          2
        ],
        [
          2
        ],
        [
          2
        ],
        [
          2
        ]
      ],
      "api_cl_list": [
        -1,
        [
          0
        ],
        [
          1
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ]
      ],
      "api_damage": [
        -1,
        [
          0
        ],
        [
          13
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ]
      ]
    },
    "api_raigeki": {
      "api_frai": [
        -1,
        4,
        4,
        4,
        4,
        4,
        3
      ],
      "api_erai": [
        -1,
        0,
        0,
        5,
        2,
        0,
        0
      ],
      "api_fdam": [
        -1,
        0,
        18,
        0,
        0,
        9,
        0
      ],
      "api_edam": [
        -1,
        0,
        0,
        44,
        122,
        0,
        0
      ],
      "api_fydam": [
        -1,
        0,
        44,
        42,
        0,
        36,
        44
      ],
      "api_eydam": [
        -1,
        0,
        0,
        9,
        18,
        0,
        0
      ],
      "api_fcl": [
        -1,
        0,
        1,
        1,
        0,
        1,
        1
      ],
      "api_ecl": [
        -1,
        0,
        0,
        1,
        1,
        0,
        0
      ]
    }
  }
}
```

@Javran maybe you will be interested in this :smile: 

Nothing much change, except for the addition of `_combined` thing for the second fleet. The main fleet and abyssal fleet still are the same.

**Comment by Javran** [comment] 2015-08-11 02:52
@bamboo3250 thanks for the data! I've never used combined fleet before so might need some time to investigate, will do it ASAP.

**Comment by ReiFan49** [comment] 2015-08-11 02:58
the combined fleet type determines either `1..6` vs `13..18` or `7..12` vs `13..18`
and hougeki phase only gives enemy range from `7..12` just like the normal hougeki ones...

**Comment by bamboo3250** [comment] 2015-08-11 03:09
More data about using Fleet Command Facility
`/kcsapi/api_req_combined_battle/goback_port`
```
svdata={"api_result":1,"api_result_msg":"\u6210\u529f"}
```


`/kcsapi/api_req_combined_battle/battle_water` (with FCF)
```
{
  "api_result": 1,
  "api_result_msg": "成功",
  "api_data": {
    "api_deck_id": "1",
    "api_ship_ke": [
      -1,
      534,
      534,
      530,
      530,
      -1,
      -1
    ],
    "api_ship_lv": [
      -1,
      50,
      50,
      50,
      50,
      -1,
      -1
    ],
    "api_nowhps": [
      -1,
      53,
      47,
      9,
      44,
      71,
      92,
      37,
      37,
      19,
      19,
      -1,
      -1
    ],
    "api_maxhps": [
      -1,
      53,
      57,
      48,
      56,
      92,
      92,
      37,
      37,
      19,
      19,
      -1,
      -1
    ],
    "api_nowhps_combined": [
      -1,
      13,
      32,
      30,
      32,
      32,
      38
    ],
    "api_maxhps_combined": [
      -1,
      32,
      32,
      32,
      32,
      32,
      45
    ],
    "api_midnight_flag": 1,
    "api_eSlot": [
      [
        515,
        515,
        513,
        -1,
        -1
      ],
      [
        515,
        515,
        513,
        -1,
        -1
      ],
      [
        513,
        513,
        -1,
        -1,
        -1
      ],
      [
        513,
        513,
        -1,
        -1,
        -1
      ]
    ],
    "api_eKyouka": [
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ]
    ],
    "api_fParam": [
      [
        78,
        74,
        42,
        73
      ],
      [
        84,
        84,
        37,
        77
      ],
      [
        25,
        0,
        63,
        52
      ],
      [
        82,
        84,
        53,
        79
      ],
      [
        105,
        0,
        94,
        90
      ],
      [
        102,
        0,
        90,
        92
      ]
    ],
    "api_eParam": [
      [
        0,
        86,
        0,
        30
      ],
      [
        0,
        86,
        0,
        30
      ],
      [
        0,
        42,
        0,
        7
      ],
      [
        0,
        42,
        0,
        7
      ],
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ]
    ],
    "api_fParam_combined": [
      [
        48,
        79,
        34,
        49
      ],
      [
        48,
        79,
        27,
        49
      ],
      [
        35,
        79,
        36,
        49
      ],
      [
        50,
        80,
        28,
        49
      ],
      [
        50,
        80,
        24,
        49
      ],
      [
        66,
        79,
        37,
        69
      ]
    ],
    "api_escape_idx": [
      3
    ],
    "api_escape_idx_combined": [
      2
    ],
    "api_search": [
      1,
      5
    ],
    "api_formation": [
      "11",
      5,
      4
    ],
    "api_stage_flag": [
      1,
      0,
      0
    ],
    "api_kouku": {
      "api_plane_from": [
        [
          -1
        ],
        [
          -1
        ]
      ],
      "api_stage1": {
        "api_f_count": 0,
        "api_f_lostcount": 0,
        "api_e_count": 0,
        "api_e_lostcount": 0,
        "api_disp_seiku": 1,
        "api_touch_plane": [
          -1,
          -1
        ]
      },
      "api_stage2": null,
      "api_stage3": null,
      "api_stage3_combined": null
    },
    "api_support_flag": 0,
    "api_support_info": null,
    "api_opening_flag": 1,
    "api_opening_atack": {
      "api_frai": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_erai": [
        -1,
        6,
        3,
        0,
        0,
        0,
        0
      ],
      "api_fdam": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_edam": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_fydam": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_eydam": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_fcl": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_ecl": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "api_hourai_flag": [
      0,
      0,
      1,
      1
    ],
    "api_hougeki1": null,
    "api_hougeki2": null,
    "api_hougeki3": {
      "api_at_list": [
        -1,
        6,
        1,
        5,
        3,
        4
      ],
      "api_at_type": [
        -1,
        0,
        0,
        0,
        0,
        0
      ],
      "api_df_list": [
        -1,
        [
          7
        ],
        [
          10
        ],
        [
          10
        ],
        [
          7
        ],
        [
          7
        ]
      ],
      "api_si_list": [
        -1,
        [
          102
        ],
        [
          -1
        ],
        [
          -1
        ],
        [
          -1
        ],
        [
          -1
        ]
      ],
      "api_cl_list": [
        -1,
        [
          1
        ],
        [
          2
        ],
        [
          1
        ],
        [
          1
        ],
        [
          1
        ]
      ],
      "api_damage": [
        -1,
        [
          2
        ],
        [
          15
        ],
        [
          14
        ],
        [
          4
        ],
        [
          3
        ]
      ]
    },
    "api_raigeki": {
      "api_frai": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_erai": [
        -1,
        5,
        1,
        6,
        0,
        0,
        0
      ],
      "api_fdam": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_edam": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_fydam": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_eydam": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_fcl": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_ecl": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  }
}
```

When using FCF, `api_escape_idx` and `api_escape_idx_combined` are added to the data to indicate which ship is not involved in the battle but we can only see this when engaging the battle.

**Comment by ReiFan49** [comment] 2015-08-11 03:10
no parameter/header from the `goback_port` ?

**Comment by bamboo3250** [comment] 2015-08-11 03:18
Yeah, it was empty like that. The information about escaped ships is included in `battleresult`, which appears before `goback_port`

`/api_req_combined_battle/battleresult`
```
{
  "api_result": 1,
  "api_result_msg": "成功",
  "api_data": {
    "api_ship_id": [
      -1,
      527,
      527,
      622,
      622,
      575,
      575
    ],
    "api_win_rank": "A",
    "api_get_exp": 80,
    "api_mvp": 6,
    "api_mvp_combined": 6,
    "api_member_lv": 103,
    "api_member_exp": 2269533,
    "api_get_base_exp": 170,
    "api_get_ship_exp": [
      -1,
      255,
      170,
      170,
      170,
      170,
      340
    ],
    "api_get_ship_exp_combined": [
      -1,
      255,
      170,
      170,
      170,
      170,
      340
    ],
    "api_get_exp_lvup": [
      [
        153593,
        155500
      ],
      [
        220404,
        228000
      ],
      [
        108540,
        112800
      ],
      [
        220066,
        228000
      ],
      [
        580743,
        584500
      ],
      [
        587732,
        606500
      ]
    ],
    "api_get_exp_lvup_combined": [
      [
        99806,
        103500
      ],
      [
        68291,
        70300
      ],
      [
        54703,
        56100
      ],
      [
        52680,
        52800,
        56100
      ],
      [
        51570,
        52800
      ],
      [
        70172,
        70300,
        74100
      ]
    ],
    "api_dests": 4,
    "api_destsf": 0,
    "api_quest_name": "ソロモン海",
    "api_quest_level": 9,
    "api_enemy_info": {
      "api_level": "",
      "api_rank": "",
      "api_deck_name": "前衛艦隊"
    },
    "api_first_clear": 0,
    "api_get_flag": [
      0,
      0,
      0
    ],
    "api_get_eventflag": 0,
    "api_get_exmap_rate": 0,
    "api_get_exmap_useitem_id": 0,
    "api_escape_flag": 1,
    "api_escape": {
      "api_escape_idx": [
        3
      ],
      "api_tow_idx": [
        8,
        9,
        10,
        11
      ]
    }
  }
}
```

**Comment by ReiFan49** [comment] 2015-08-11 03:42
is `api_escape` on `battleresult` means, the one taiha'd ?
is `api_tow` on `battleresult` means, possible to tow the escaping one?

**Comment by bamboo3250** [comment] 2015-08-11 04:23
@ReiFan49 It seems so for both fields and only the first ship of each array will be excluded from the next battle.

**Comment by dragonjet** [comment] 2015-08-11 04:42
`api_escape_idx` is the taiha
`api_tow_idx` is the escort going back

**Comment by LostLogia4** [comment] 2015-08-11 06:31
@bamboo3250 Can you please move all that API calls to pastebin? We're scrolling through a really long sutra here.

**Comment by bamboo3250** [comment] 2015-08-11 06:44
@LostLogia4 sure, done :sweat_smile:

**Comment by LostLogia4** [comment] 2015-08-11 06:50
Now that's better. That being said though, is there any way to construct collapsible textboxes in these issue threads...

**Comment by bamboo3250** [comment] 2015-08-11 08:32
@Javran some more data for you
http://pastebin.com/XVMaFMy9
http://pastebin.com/ELjNDASi (submarine node)

For Surface Task Force 
`api_hougeki1` is the first phase between main fleet and abyssal.
`api_hougeki2` is the second phase between main fleet and abyssal when BB is involved.
`api_hougeki3` is the phase between escort fleet and abyssal.
`api_raigeki` is the closing torpedo between escort fleet and abyssal.

**Comment by Javran** [comment] 2015-08-12 03:25
@bamboo3250 @ReiFan49 just got some spare time and figured out what's in the data, thanks for the info!

Please correct me if any of the following is incorrect:

* Data in `api_hougekiX` and `api_raigeki` are just normal, the index is always within `1..12` but the "friendly" side might be either escort fleet or main fleet

* `_combined` fields are for escort fleets.

I guess I have to make a new API for combined fleets. seems like there is no combined fleet type indicator from the data, does different type of combined fleets use different API in the game?

Also there are more works to do for #589, for now it doesn't make sense to me how come `api_damage` was not present, so might need some data for analysis.

**Comment by dragonjet** [comment] 2015-08-12 04:22
`PlayerManager.combinedFleet` should contain the combined state
0 = not combined
1 = not sure which is surface or carrier
2 = not sure which is surface or carrier

**Comment by ReiFan49** [comment] 2015-08-12 04:26
@dragonjet i got 2, for 
Akashi, Yuubari, Nagato, Maya
Naka, Z1, Fubuki, Maruyu

@Javran how about the other api such as `opening_attack` and `kouku` ?

**Comment by ethrundr** [comment] 2015-08-12 09:52
#594 Bug: Prediction for Escort Fleet was added to the main fleet

**Comment by Javran** [comment] 2015-08-12 15:57
Update: working on surface task force and it's now working:

![2015-08-12_114543_3360x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9228709/b0b962ec-40e7-11e5-9325-06aab63d6ea9.png)

I guess the night battle for combined fleet also needs some adjustment as the only the escort fleet is involved, does anyone have the data?

Meanwhile I find some interesting note [here](https://github.com/andanteyk/ElectronicObserver/blob/master/ElectronicObserver/Other/Information/apilist.txt) (search keyword "機動部隊"),
if the API response doesn't change overtime, I guess I can figure out carrier task force too.

@ReiFan49 openning attacks are between escort fleet and enemy fleet, the format is the same as regular battles. For `kouku` there are two fields that records the damage dealt on both side: `api_stage3` and `api_stage3_combined`, in which `api_fdam` are damage took by friendly fleet, and `api_edam` (`api_stage3_combined` doesn't have this field) are damage took by enemy fleet.

**Comment by bamboo3250** [comment] 2015-08-12 16:02
@Javran Here is the data I just collected from E3 using Carrier Task Force 
http://pastebin.com/rGAdEmHM

For this one, it still show `Uncaught TypeError: Cannot read property 'api_damage' of undefined` in the battle.

**Comment by Javran** [comment] 2015-08-12 16:09
@bamboo3250 thanks for the data, now I know what's wrong xD.

**Comment by bamboo3250** [comment] 2015-08-12 16:10
nice :smile:  :+1:

**Comment by Javran** [comment] 2015-08-12 16:15
@bamboo3250 btw did you eliminate all enemies even before main fleet's shelling stage? This is so far I can tell from the data, just want to confirm.

**Comment by bamboo3250** [comment] 2015-08-12 16:20
@Javran that's correct. And it is a perfect S so no damage to my fleet.

btw, this is data of air battle for Carrier Task force. It has some more "_combined" things in api_kouku.

**Comment by Javran** [comment] 2015-08-12 16:26
@bamboo3250 actually there's no much difference from surface task force. that error was because I made a wrong assumption about the data: I assumed when `api_hourai[1] == 1` the `api_hougeki2`  field must exist so an attempt of doing `api_hougeki2.api_damage` resuits in that error.

**Comment by bamboo3250** [comment] 2015-08-12 16:30
I see, so now the problem is only which fleet will take damage, right?

**Comment by Javran** [comment] 2015-08-12 16:34
@bamboo3250 yes, also I suspect my night battle prediction might be wrong because only the escort fleet is involved, whose HP are likely to be contained in `api_nowhps_combine`, rather than `api_nowhps`, but I might need some data to verify this.

**Comment by bamboo3250** [comment] 2015-08-12 16:39
@Javran Actually it has `api_nowhps_combine` in night battle. Here is the night battle at boss node E3 just now. My fleet got rekt so hard :sob: 

/kcsapi/api_req_combined_battle/midnight_battle
http://pastebin.com/mdUg63iR

**Comment by Javran** [comment] 2015-08-12 16:53
@bamboo3250 sorry to hear that :( just took a look at the data, I guess for now what's happening is the damage got calculated on main fleet while it is supposed to be on the escort fleet?

**Comment by bamboo3250** [comment] 2015-08-12 17:01
Yes, that is the main (and only) problem atm. We need to define clearly the direction of damage for 2 types of combined fleets in day battle. Meanwhile, night battle only happens between escort and abyssal though. 

And don't worry about my collecting data. I just say hi to the boss and let my Akizuki play around with their CV xD

**Comment by Javran** [comment] 2015-08-12 18:48
I've added few APIs dealing with combined fleets (see #602 for detail). As I'm not familiar with the codebase, can someone take over the remaining task (integrate it with existing code)?

**Closed** 2015-08-14 09:49 UTC
Labels: other

**Comment by dragonjet** [comment] 2015-08-14 09:50
By the release of v17, unfinished issues and tasks will be further tracked on #633
