### ISSUE TITLE
Crashing when notification occured

### ISSUE THREAD

**Issue by convoicon** [dragonjet/KC3Kai#734] opened 2015-08-27 01:48 UTC
This makes my whole google chrome browser crashed whenever there is a notification sound pop up!

**Comment by Crazyteitoku** [comment] 2015-08-27 02:23
Please provide more background information such as the versions you are using for chrome, KC3 Kai, OS, etc.

Also have you tried using other notification sounds via settings and/or disabled the notification sound completely?

**Comment by convoicon** [comment] 2015-08-27 02:51
This is my setting, Chrome Version 44.0.2403.157 dev-m, window 8.1, Kc3 Version 18.2 and my setting for the sound 
![image](https://cloud.githubusercontent.com/assets/13990697/9511459/0055f0d8-4cb2-11e5-82cc-56843867de35.png)

**Comment by convoicon** [comment] 2015-08-27 02:52
I have also disable the notification, but everytime something finished, my chrome crashed with no mercy.

**Comment by convoicon** [comment] 2015-08-27 04:05
https://vid.me/LblT
this is the example what i am talking about

**Comment by Crazyteitoku** [comment] 2015-08-27 08:41
Looks like it is a seg(mentation) fault. Were there any errors from within Event viewer? You might also want to even try running Chrome via command line as well.

I must also ask, what do you meant by "dev-m"? is that what is printed from within chrome when you go into chrome://system? If so, are you running a developer build of Chrome by some chance? Also have you tried giving Chromium a shot?

**Comment by convoicon** [comment] 2015-08-27 09:04
I just print what it said on the screen lol.
I am running a normal chrome
I love your Kc3 but now it crashed so much I will temporary use Kcv
Can you help me to fix it?
What is running chrome via command line?

**Comment by Crazyteitoku** [comment] 2015-08-27 10:08
Often the first steps are usually to try and troubleshoot the issue, find out where it is coming from. Without a detailed debugging information, fixing it would be like trying to perform a magic to do everything blindfolded because not there still isn't enough information available to know where it is coming from.

When you said you have tried disabling notification, do you mean you have also tried disabling desktop notifications as well as the notification sound? If so, once you have set those have you tried re-opening KC3 Kai again (or ideally Chrome)?

By event viewer I meant [this](https://www.winhelp.us/event-viewer-in-windows.html). Usually when a program crashes or when there's issues with your windows it will logged there and so the best place to start would be there. 

Also when I meant Chromium I meant [this](http://chromium.woolyss.com/).

Last but not least, [here](http://www.wikihow.com/Run-a-Program-on-Command-Prompt#Opening_the_Command_Prompt_sub) is how to run a program through a command prompt.

Just thinking alongside. Could it be by any chance one of your extensions from within chrome may also be causing the issue? I mean it could be a buggy extension apart from KC3 Kai itself that is causing it. Along with that, could also be that your computer running out memory?

**Comment by convoicon** [comment] 2015-08-27 11:06
DIsabling notification, yes i did both of it, but the problem lied in when something is done, my Chrome just crashed
I have 8gb of ram so there can't be running out of memory
I will check the event viewer then send you the result.
Thank you.

**Comment by convoicon** [comment] 2015-08-27 11:16
https://drive.google.com/file/d/0B3aaUjr4D82GcXd4bDlmbW1tVms/view?usp=sharing
this is the event file from the Chrome crashed

**Comment by Crazyteitoku** [comment] 2015-08-27 11:40
Yeah, the funny thing is that even when the notifications has been disabled it sounds like it might not even be coming from KC3 Kai but something is buggy about that Chrome build or it might even come from somewhere else.

I hate to admit this but even on 8GB of RAM is somewhat barely enough for modern and popular browsers. I don't use windows here and over prolonged periods of time Chromium would start becoming very slow before being unresponsive. Often at times I need to resort to restarting Chromium manually and seeing if I can free up some more memory there. You may want to keep  watch of your processes with something like [Process Explorer] (https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx). Over time with closing and opening new tabs within Chrome for instance may start building up resource consumption. That is not to say however that there is necessarily a connection with high memory/resources consumption be related to a crash that seems to occur on a very specific instance. Then again it is probably worth noting.

Another thought comes to mind is that have you tried other extensions which makes use of the Chrome notifications? examples of other extensions may include the likes of [LightShot] (https://app.prntscr.com/en/index.html). If you use those, you may want to see if they work with the notifications in general.

Thanks for providing the event viewer dump, however I am unable to view this file as there are no free viewers readily available for my platform. Can you please provide the information in an alternative format? be it a text based output or perhaps a screenshot may help.

**Comment by convoicon** [comment] 2015-08-27 11:53
I think the problem lied on my Chrome
It just instants crash
I think this is not the Kc3 fault. I should reinstall the Chrome.
And here is the Event log 
![image](https://cloud.githubusercontent.com/assets/13990697/9519886/b8640dc2-4cfd-11e5-8628-1cacca02fa20.png)

**Comment by Crazyteitoku** [comment] 2015-08-27 12:41
Ah yup that somewhat does look like it appears to be coming from Chrome itself. Another way to troubleshoot the issue is to try Chromium anyway.

**Comment by convoicon** [comment] 2015-08-27 13:39
Thank you for your help, you can close this topic now :)

**Comment by Crazyteitoku** [comment] 2015-08-27 13:50
No problem. Has it been fixed though? I'll mark it as closed for now. :laughing:

**Closed by Crazyteitoku** 2015-08-27 13:50 UTC
